name: tennis_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.4.5

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: 1.2.0
  flutter_easyloading: 3.0.5
  flutter_spinkit: 5.2.0
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  cupertino_icons: 1.0.6
  get: 4.6.6
  flutter_bloc: ^8.1.4
  socket_io_client: 2.0.3+1
  fl_chart: ^0.66.2
  url_launcher: ^6.2.5
  carousel_slider: 4.2.1
  flutter_svg: ^2.0.10+1
  search_choices: 2.2.7
  pdf: ^3.10.8
  printing: ^5.12.0
  pie_chart: 5.4.0
  #flutter_vlc_player: 7.4.1
  firebase_messaging: ^14.7.19
  firebase_core: ^2.27.0
  flutter_local_notifications: ^17.0.0
  timeago: 3.6.1
  blurrycontainer: ^1.0.2
  cached_network_image: ^3.3.1
  group_button: ^5.3.4
  uuid: ^4.4.0
  skeletonizer: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.22.0
  mockito: ^5.4.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2

  flutter_lints: ^3.0.1

flutter_native_splash:
  color: '#001242'
  image: 'assets/LaunchImage.png'

# Launch icon config
flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/iconHome.png'
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: 'assets/iconHome.png'
    background_color: '#hexcode'
    theme_color: '#hexcode'
  windows:
    generate: true
    image_path: 'assets/iconHome.png'
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: 'assets/iconHome.png'
flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
